
### GET BC INFO
POST http://localhost:1337/app HTTP/1.1
Content-Type: application/json

{
  "method": "cerera.chain.getInfo",
  "id": 121,
  "jsonrpc": "2.0",
}

### GET BLOCK INFO
POST http://localhost:1337/app HTTP/1.1
Content-Type: application/json

{
    "method": "get_block",
    "jsonrpc": "2.0",
    "id": 6525,
    "params": [0]
}

### GET LIST OF ACCOUNTS
POST http://localhost:1337/app HTTP/1.1
Content-Type: application/json

{
    "method": "cerera.account.getAll",
    "jsonrpc": "2.0",
    "id": 3
}

### GET BALANCE OF ADDRESS
POST http://localhost:1337/app HTTP/1.1
Content-Type: application/json

{
    "method": "get_balance",
    "jsonrpc": "2.0",
    "id": 33,
    "params":[
        "0x99943a02570104c136a42cd4e16ba7b1cb76d0ac5463004c6805cae9b50d2f4ce0b1847d6ecf9db7f2840c108616e038"
    ]
}

### CREATE ACCOUNT
POST http://localhost:1337/app HTTP/1.1
Content-Type: application/json

{
    "method": "cerera.account.create",
    "jsonrpc": "2.0",
    "id": 11231,
    "params": [
        "test_password"
    ]
}

### RESTORE ACCOUNT
POST http://localhost:1337/app HTTP/1.1
Content-Type: application/json

{
    "method": "cerera.account.restore",
    "jsonrpc": "2.0",
    "id": 2,
    "params": [
        "holiday journey object dirt turn there clown picnic legend average organ dose obey viable october park wood license elephant spell tiger horror exhaust also",
        "test_password"
    ]
}

### VERIFY ACCOUNT
POST http://localhost:1337/app HTTP/1.1
Content-Type: application/json

{
    "method": "verify_account",
    "jsonrpc": "2.0",
    "id": 11231,
    "params": [
        "0x1b9e0917a36263c3ec6c1518e7b99e972f0915c1f033884b8956e2f3b686b1c385127d2bb3dd633d143893961f7839a2",
        "test_password"
    ]
}

### FAUCET
POST http://localhost:1337/app HTTP/1.1
Content-Type: application/json

{
    "method": "faucet",
    "jsonrpc": "2.0",
    "id": 11231,
    "params": [
        "0xaaaf6e4794289b74241bdb9f1b6197cf4b9b17114b3ca69c1bc01f011d9ccc26",
        10
    ]
}

### POOL
POST http://localhost:1337/app HTTP/1.1
Content-Type: application/json

{
    "method": "cerera.pool.getInfo",
    "jsonrpc": "2.0",
    "id": 11231,
    "params": []
}

### GET TX
POST http://localhost:1337/app HTTP/1.1
Content-Type: application/json

{
    "method": "get_tx",
    "jsonrpc": "2.0",
    "id": 11231,
    "params": ["0xff9bdd19ec14fca1eb576a6aa5d0b69e660bab21365028ccc642307bed733596"]
}


### INFO
POST http://localhost:1337/app HTTP/1.1
Content-Type: application/json

{
    "method": "info",
    "jsonrpc": "2.0",
    "id": 11231
}


###

POST http://localhost:1337/app HTTP/1.1
Content-Type: application/json

{
    "method": "miner.status",
    "jsonrpc": "2.0",
    "id": 11231
}
###
POST http://localhost:1337/app HTTP/1.1
Content-Type: application/json

{
    "method": "chain.getMinimumGasValue",
    "jsonrpc": "2.0",
    "id": 11231
}   

### GET INPUTS
POST http://localhost:1337/app HTTP/1.1
Content-Type: application/json

{
    "method": "cerera.account.inputs",
    "jsonrpc": "2.0",
    "id": 11231,
    "params": ["0xf50a50974397f8caa8c9fd37b438d00f54e71a4795007024bcb0f7492ca773ba"]
}

### GET ALL ACCOUNTS
POST http://localhost:1337/app HTTP/1.1
Content-Type: application/json

{
  "method": "cerera.account.getAll",
  "params": [],
  "id": 11
}